

spring:
  application:
    name: "authentication-service"
  data:
    mongodb:
      host: 45.119.83.217
      port: 54324
      username: dochero
      password: ksharkinc2022
      database: dochero-authentication-db
  output:
    ansi:
      enabled: always
server:
  error:
    include-stacktrace: never
  port: "8081"
eureka:
  client:
    service-url:
#      defaultZone: http://45.119.85.106:40000/eureka
      defaultZone: http://localhost:8761/eureka
springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /api-docs
app:
  jwt:
    secret: abcdefghijklmnOPQRSTUVWXYZ
