name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  version: ${{ github.sha }}
  dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
  dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest
  

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Maven Build;
      run: 
        cd authentication-service;
        sh mvnw clean -DskipTests=true package;
    
    - name: Build Docker image
      run:
        cd authentication-service;
        docker build . --file Dockerfile --tag phongvanngo/dochero-authentication-service:latest;
        docker tag phongvanngo/dochero-authentication-service:latest phongvanngo/dochero-authentication-service:$version;
        
    - name: Push Docker Image
      run:
        docker login --username=${dockerhub_username} --password=${dockerhub_password};
        docker push phongvanngo/dochero-authentication-service:$version;
        docker push phongvanngo/dochero-authentication-service:latest;
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: executing remote ssh to DrDongPhuong commands using password 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: cd /home/novapo/docker-compose-list/dochero/;git pull;docker stop dochero-authentication-service;docker rm dochero-authentication-service; docker pull phongvanngo/dochero-authentication-service;docker-compose -f authentication.docker-compose.yml  up -d ; 
